### ISSUE TITLE
need support with the idea of using simple variables in new_resource.user

### ISSUE THREAD

**Issue by bish0polis** [ncerny/facl#5]
I need some help, and I'm having trouble reading resources/facl.rb

I have this:
```
     facl k do
      user     :'' => 'rwx', nginx: 'r-x'
       group    :'' => 'r-x'
      mask     :'' => 'r-x'
       other    :'' => 'r-x'
      default  :user =>  { :'' => 'rwx', nginx: 'r-x' },
                :group => { :'' => 'r-x' },
               :mask =>  { :'' => 'r-x' },
               :other => { :'' => 'r-x' }
    end if File.exist?(k)
```

But I want to sometimes facl it to `{default:,}user:xnign:rwx` instead -- ie another user instead.  I want to use a variable there, but that's a string literal.

Help out my tired brain?  How does one *do* that?  I was close with 
```
somename='nginx'
:
:
      user     :'' => 'rwx', somename => 'r-x'
:
```

... but no dice:
```
testytest     - Would Setting Default ACL (user:nginx:remove) on /srv/nginxroot/awesomedir
testytest     - Would Setting Default ACL (user:nginx:r-x) on /srv/nginxroot/awesomedir
```
... over and over, every invocation ...

I feel I'm close, but I'm also close to mental collapse.  Any hints?

**Comment by ncerny** [comment]
Sorry for the months-late reply...

it's a ruby hash, so you'll probably need to do something like:

`user. :'' => 'rwx', "#{your_variable_name}" => 'r-x'`
