### ISSUE TITLE
please add provides 'facl' to resource to support chef 16.2.44 changes

### ISSUE THREAD

**Issue by nanolonny** [ncerny/facl#9]
(https://docs.chef.io/release_notes_client/#breaking-change-in-resources)

In short:

**Pre-16 code:**

`resource_name :foo`

**Chef Infra Client 16+ code**

`provides :foo`

**Chef Infra Client < 16 backwards compatible code**

```
resource_name :foo
provides :foo
```

**Comment by ncerny** [comment]
Resolved in Master.
